$ANSIBLE_VAULT;1.1;AES256
61613765636335613466653534383166356634383762366335626166386164656537323262356662
3832306264623338393134396132663539616230616163340a653535323063616238636231316133
35373963626632353264396361343861636265306261383632633331653235356666373765613030
3235303538383363330a656331646663613838663664623630623264643138663039373137623634
31656364623038636333393666313831386639363564376236316534336664363030333435383566
32316236623232653932363562356163623033326564633063303933376264323431306538356564
33313930336164623762393561393635616632346233663138366266346333373932383831336661
64643239653662363365346634613434393132616436633837393363616265343732623163306638
64326563363832333232323965396331666130633830383461626137366130656339303731646639
39633962666563313163656135376633653631363430303065373738626338336562313537343132
63313532626235626439396434323831643661663164333562313637383134646264396235653864
30393339396366393537336531393366363266346233316631386132303233316238653764306637
6266
